# Generated by Django 2.2 on 2019-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip_position',
            field=models.CharField(default='', max_length=100, verbose_name='ip position'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_agent',
            field=models.CharField(default='', max_length=300, verbose_name='user-agent'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
