# Generated by Django 2.2 on 2019-04-26 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import live2d.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Live2dAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Live2dAction Name')),
                ('motions', models.FileField(upload_to=live2d.models.upload_motions_path, verbose_name='Live2dAction motions')),
            ],
            options={
                'verbose_name': 'live2dAction',
                'verbose_name_plural': 'live2dAction',
            },
        ),
        migrations.CreateModel(
            name='Live2dTextures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Live2dTextures Name')),
                ('textures', models.ImageField(upload_to=live2d.models.upload_textures_path, verbose_name='Live2dTextures  Clothes')),
            ],
            options={
                'verbose_name': 'live2dTextures',
                'verbose_name_plural': 'live2dTextures',
            },
        ),
        migrations.CreateModel(
            name='Live2d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Live2d Name')),
                ('file_model', models.FileField(blank=True, null=True, upload_to=live2d.models.upload_path, verbose_name='Live2d model')),
                ('moc', models.FileField(upload_to=live2d.models.upload_path, verbose_name='Live2d moc')),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live2d.Live2dAction')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live2d.Live2dTextures')),
            ],
            options={
                'verbose_name': 'live2d',
                'verbose_name_plural': 'live2d',
            },
        ),
    ]
