# Generated by Django 2.1.3 on 2018-12-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '关于', 'verbose_name_plural': '关于'},
        ),
    ]
