# Generated by Django 2.2 on 2019-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='/static/images/avater.jpg', help_text='头像', null=True, upload_to='static/images/user', verbose_name='头像'),
        ),
    ]
