# Generated by Django 2.2 on 2019-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': '友人帐', 'verbose_name_plural': '友人帐'},
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=50, verbose_name='友人帐'),
        ),
    ]
