# Generated by Django 2.1.3 on 2018-12-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='desc',
        ),
        migrations.AddField(
            model_name='blog',
            name='summary_img',
            field=models.ImageField(default='', upload_to='static/images/summary', verbose_name='摘要图片'),
        ),
    ]
