# Generated by Django 2.1.4 on 2019-01-05 10:26

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('openid', models.CharField(default='', max_length=100, verbose_name='openid')),
                ('type', models.CharField(choices=[('1', 'github'), ('2', 'qq'), ('3', 'weibo')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
