# Generated by Django 2.2 on 2019-04-26 09:22

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QqWry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('qqwry_file', models.FileField(upload_to='static/qqwry', verbose_name='QqWry')),
            ],
            options={
                'verbose_name': 'QqWry',
                'verbose_name_plural': 'QqWry',
            },
        ),
    ]
