# Generated by Django 2.2 on 2019-04-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qq_wry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqwry',
            name='qqwry_file',
            field=models.FileField(blank=True, null=True, upload_to='static/qqwry', verbose_name='QqWry'),
        ),
    ]
